### ISSUE TITLE
cosmo

### ISSUE THREAD

**Issue by EGLadona** [quimbp/cosmo#1]
Recordar en el apartado de la documentación ("Instalación") que para instalar en directorios diferentes de ($HOME)/cosmo hay que revisar el fiochero make.inc y modificar la línea:

COSMO = $(HOME)/cosmo

por

COSMO = /my_path/cosmo

Si no el make falla al buscar directorios.

Emilio

**Comment by quimbp** [comment]
With the version 2.0, this is no longer required. The variable COSMO is no longer defined in make.inc, and the only changes required in the make.inc file are those related to changes in compilator or compilation options.
