### ISSUE TITLE
Problem when I try to install

### ISSUE THREAD

**Issue by AdrianAsac** [quimbp/cosmo#2]
Hi, I'm trying to install cosmo in a ubuntu16.04 server with hdf5-1.10.4 and zlib-1.2.11

When I execute "make install", I receive this error:

use netcdf
    1
Fatal Error: Can't open module file 'netcdf.mod' for reading at (1): No such file or directory
Makefile:11: recipe for target 'cdf.o' failed
make[1]: *** [cdf.o] Error 1
make[1]: Leaving directory '/var/cosmo/src/lib'
Makefile:16: recipe for target 'COSMO' failed
make: *** [COSMO] Error 2

If I search for “netcdf.mod” , I haven’t this file in My server

I attach you my make.inc file.
[make.zip](https://github.com/quimbp/cosmo/files/2585336/make.zip)

Can you help me? 
Have you got any guide about the installation process?

Thank you!

**Comment by quimbp** [comment]
In ubuntu you neet to install the netcdf bin, libraries and modules:

sudo apt-get install netcdf-bin
sudo apt-get install libnetcdff-dev

The Makefile now try to locate the location of modules and libraries with the help of the nc-config utility. In the file make.inc, now we have:

NF90_INC = $(shell nc-config --includedir)
NF90_LIB = $(shell nc-config --libdir)
