### ISSUE TITLE
Bugs with the tconsola() and message passing in contouring SST images and tool.geocdf

### ISSUE THREAD

**Issue by EGLadona** [quimbp/cosmo#6]

**Comment by EGLadona** [comment]
In drawing(), line with:

    self.SAIDIN.icdf = tools.geocdf(self.SAIDIN.FILENAME.get())

should pass the consola reference

    self.SAIDIN.icdf = tools.geocdf(self.SAIDIN.FILENAME.get(),wid=self.cons)

In contourplot(), MESSAGE is a property of PLOT not IFIELD, so 

     IFIELD.MESSAGE

should be

    PLOT.MESSAGE

**Comment by quimbp** [comment]
Modified drawing.py and contourplot.py.
